/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as AuthenticatedEspaceMembreRouteImport } from './routes/_authenticated/espace-membre'
import { Route as AuthenticatedFiliereRouteImport } from './routes/_authenticated/filiere'
import { Route as ActualitesIndexRouteImport } from './routes/actualites.index'
import { Route as ActualitesIdRouteImport } from './routes/actualites.$id'
import { Route as ActualitesCreerRouteImport } from './routes/actualites.creer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceMembreRoute =
  AuthenticatedEspaceMembreRouteImport.update({
    id: '/espace-membre',
    path: '/espace-membre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFiliereRoute = AuthenticatedFiliereRouteImport.update({
  id: '/filiere',
  path: '/filiere',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ActualitesRoute,
} as any)
const ActualitesIdRoute = ActualitesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActualitesRoute,
} as any)
const ActualitesCreerRoute = ActualitesCreerRouteImport.update({
  id: '/creer',
  path: '/creer',
  getParentRoute: () => ActualitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRouteWithChildren
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/espace-membre': typeof AuthenticatedEspaceMembreRoute
  '/filiere': typeof AuthenticatedFiliereRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites/creer': typeof ActualitesCreerRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/espace-membre': typeof AuthenticatedEspaceMembreRoute
  '/filiere': typeof AuthenticatedFiliereRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites/creer': typeof ActualitesCreerRoute
  '/actualites': typeof ActualitesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/actualites': typeof ActualitesRouteWithChildren
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/_authenticated/espace-membre': typeof AuthenticatedEspaceMembreRoute
  '/_authenticated/filiere': typeof AuthenticatedFiliereRoute
  '/actualites/$id': typeof ActualitesIdRoute
  '/actualites/creer': typeof ActualitesCreerRoute
  '/actualites/': typeof ActualitesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/auth'
    | '/club'
    | '/contact'
    | '/galerie'
    | '/espace-membre'
    | '/filiere'
    | '/actualites/$id'
    | '/actualites/creer'
    | '/actualites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/club'
    | '/contact'
    | '/galerie'
    | '/espace-membre'
    | '/filiere'
    | '/actualites/$id'
    | '/actualites/creer'
    | '/actualites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actualites'
    | '/auth'
    | '/club'
    | '/contact'
    | '/galerie'
    | '/_authenticated/espace-membre'
    | '/_authenticated/filiere'
    | '/actualites/$id'
    | '/actualites/creer'
    | '/actualites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActualitesRoute: typeof ActualitesRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace-membre': {
      id: '/_authenticated/espace-membre'
      path: '/espace-membre'
      fullPath: '/espace-membre'
      preLoaderRoute: typeof AuthenticatedEspaceMembreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/filiere': {
      id: '/_authenticated/filiere'
      path: '/filiere'
      fullPath: '/filiere'
      preLoaderRoute: typeof AuthenticatedFiliereRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/actualites/$id': {
      id: '/actualites/$id'
      path: '/$id'
      fullPath: '/actualites/$id'
      preLoaderRoute: typeof ActualitesIdRouteImport
      parentRoute: typeof ActualitesRoute
    }
    '/actualites/creer': {
      id: '/actualites/creer'
      path: '/creer'
      fullPath: '/actualites/creer'
      preLoaderRoute: typeof ActualitesCreerRouteImport
      parentRoute: typeof ActualitesRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEspaceMembreRoute: typeof AuthenticatedEspaceMembreRoute
  AuthenticatedFiliereRoute: typeof AuthenticatedFiliereRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEspaceMembreRoute: AuthenticatedEspaceMembreRoute,
  AuthenticatedFiliereRoute: AuthenticatedFiliereRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ActualitesRouteChildren {
  ActualitesIdRoute: typeof ActualitesIdRoute
  ActualitesCreerRoute: typeof ActualitesCreerRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
}

const ActualitesRouteChildren: ActualitesRouteChildren = {
  ActualitesIdRoute: ActualitesIdRoute,
  ActualitesCreerRoute: ActualitesCreerRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
}

const ActualitesRouteWithChildren = ActualitesRoute._addFileChildren(
  ActualitesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActualitesRoute: ActualitesRouteWithChildren,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
